packages:
  - accountsservice
  - adw-gtk-theme
  - alsa-firmware
  - alsa-plugins
  - alsa-utils
  - amd-ucode
  - appimagelauncher
  - asusctl
  - awesome-terminal-fonts
  - base
  - base-devel
  - bash-completion
  - bind
  - bluez
  - bluez-hid2hci
  - bluez-libs
  - bluez-obex
  - bluez-utils
  - brightnessctl
  - btop
  - btrfs-assistant
  - btrfs-progs
  - cachy-update
  - cachyos-fish-config
  - cachyos-gaming-applications
  - cachyos-gaming-meta
  - cachyos-hello
  - cachyos-hooks
  - cachyos-kernel-manager
  - cachyos-keyring
  - cachyos-micro-settings
  - cachyos-mirrorlist
  - cachyos-nord-gtk-theme-git
  - cachyos-packageinstaller
  - cachyos-plymouth-bootanimation
  - cachyos-rate-mirrors
  - cachyos-settings
  - cachyos-snapper-support
  - cachyos-v3-mirrorlist
  - cachyos-v4-mirrorlist
  - cachyos-wallpapers
  - cachyos-zsh-config
  - cantarell-fonts
  - capitaine-cursors
  - cartridges
  - cava
  - chafa
  - chwd
  - code
  - cpupower
  - crun
  - cryptsetup
  - cups
  - cups-filters
  - cups-pdf
  - device-mapper
  - dgop
  - diffutils
  - discord
  - dmidecode
  - dmraid
  - dms-shell-bin
  - dnsmasq
  - doot
  - dosfstools
  - dotnet-sdk-8.0
  - dotnet-sdk-bin
  - dsearch-bin
  - duf
  - e2fsprogs
  - efibootmgr
  - efitools
  - egl-wayland
  - ethtool
  - exfatprogs
  - f2fs-tools
  - fastfetch
  - ffmpegthumbnailer
  - foomatic-db
  - foomatic-db-engine
  - foomatic-db-gutenprint-ppds
  - foomatic-db-nonfree
  - foomatic-db-nonfree-ppds
  - foomatic-db-ppds
  - fprintd
  - fsarchiver
  - ghostscript
  - ghostty
  - git
  - glances
  - glib2-devel
  - greetd-dms-greeter-git
  - gsfonts
  - gst-libav
  - gst-plugin-pipewire
  - gst-plugin-va
  - gst-plugins-bad
  - gst-plugins-ugly
  - gutenprint
  - hdparm
  - hwdetect
  - hwinfo
  - inetutils
  - iptables-nft
  - itch-bin
  - iwd
  - jfsutils
  - kbfs
  - keybase
  - kvantum-theme-nordic-git
  - less
  - lib32-mesa
  - lib32-nvidia-utils
  - lib32-opencl-nvidia
  - lib32-vulkan-radeon
  - libdvdcss
  - libfprint-goodix-521d
  - libgsf
  - libopenraw
  - libva-nvidia-driver
  - limine
  - limine-mkinitcpio-hook
  - limine-snapper-sync
  - linux-cachyos
  - linux-cachyos-headers
  - linux-cachyos-lts
  - linux-cachyos-lts-headers
  - linux-cachyos-lts-nvidia-open
  - linux-cachyos-nvidia-open
  - linux-firmware
  - logrotate
  - lsb-release
  - lsscsi
  - lvm2
  - man-db
  - man-pages
  - matugen
  - mdadm
  - meld
  - mesa-utils
  - micro
  - mkinitcpio
  - modemmanager
  - mtools
  - nano
  - nano-syntax-highlighting
  - netctl
  - networkmanager
  - networkmanager-openvpn
  - nfs-utils
  - nilfs-utils
  - niri
  - noto-fonts
  - noto-fonts-cjk
  - noto-fonts-emoji
  - nss-mdns
  - nvidia-prime
  - nvidia-settings
  - nvidia-utils
  - octopi
  - opencl-nvidia
  - openssh
  - os-prober
  - otf-font-awesome
  - pacman-contrib
  - pamixer
  - paru
  - pavucontrol
  - perl
  - pipewire-alsa
  - pipewire-pulse
  - pkgfile
  - plezy
  - plocate
  - plymouth
  - podman-compose
  - podman-docker
  - polkit-kde-agent
  - poppler-glib
  - power-profiles-daemon
  - protonup-qt
  - pv
  - python
  - python-defusedxml
  - python-packaging
  - python-periphery
  - python-pyusb
  - python-spidev
  - python-uv-build
  - qt5ct
  - quickshell-git
  - rbw
  - rebuild-detector
  - reflector
  - ripgrep
  - rog-control-center
  - rsync
  - s-nail
  - sddm
  - sg3_utils
  - smartmontools
  - snapper
  - sof-firmware
  - splix
  - sudo
  - supergfxctl
  - switcheroo-control
  - sysfsutils
  - system-config-printer
  - texinfo
  - ttf-bitstream-vera
  - ttf-dejavu
  - ttf-fira-sans
  - ttf-hack
  - ttf-hack-nerd
  - ttf-liberation
  - ttf-meslo-nerd
  - ttf-opensans
  - ufw
  - unrar
  - unzip
  - upower
  - usb_modeswitch
  - usbutils
  - vim
  - vlc
  - vlc-plugins-all
  - vulkan-radeon
  - wget
  - which
  - wireless-regdb
  - wireplumber
  - wl-clipboard
  - woff2-font-awesome
  - wpa_supplicant
  - xdg-user-dirs
  - xf86-video-amdgpu
  - xfsprogs
  - xl2tpd
  - xwayland-satellite
  - youtube-music
  - zed
systemd_user:
  app-com.mitchellh.ghostty.service: enabled
