[settings]
experimental = true

[tools]
lazygit = "latest"
go = "latest"
neovim = "latest"
node = "latest"
rust = "latest"
jqp = "latest"
yarn = "latest"
xh = "latest"
ripgrep = "latest"
delta = "latest"
bat = "latest"
jq = "latest"
github-cli = "latest"
zoxide = "latest"
starship = "latest"
kubectx = "latest"
fzf = "latest"
eza = "latest"
fx = "latest"
