[tools]
age = "latest"
"aqua:dalance/procs" = "latest"
ast-grep = "latest"
bat = "latest"
crush = "latest"
delta = "latest"
eza = "latest"
fx = "latest"
fzf = "latest"
gh = "latest"
"github:JanDeDobbeleer/aliae" = "latest"
"github:pol-rivero/doot" = "latest"
"github:pol-rivero/pkgstate" = "latest"
go = "latest"
golangci-lint = "latest"
gum = "latest"
hexyl = "latest"
imagemagick = "latest"
jq = "latest"
lazygit = "latest"
neovim = "nightly"
node = "latest"
npm = "latest"
ollama = "latest"
ripgrep = "latest"
rust = "latest"
rust-analyzer = "latest"
starship = "latest"
task = "latest"
usage = "latest"
uv = "latest"
xh = "latest"
yq = "latest"
zoxide = "latest"

[tasks.update]
description = "Run various updates"
run = [
    'doot pull',
    'cachy-update',
    'mise self-update',
    'mise upgrade',
    'code --update-extensions',
    'nvim --headless "+Lazy! sync" +qa'
]
